name: Release
# This workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version Bump Type (major, minor, patch)'
        required: true
        default: 'patch'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: /go/src/github.com/julienvinet/govh-mrm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump_version
        uses: packagrio/action-bumpr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version_bump_type: ${{ github.event.inputs.version_bump_type }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: 'julien@vinet.dev'
          author_name: 'Julien Vinet'
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - name: Commit Changes
        id: commit
        uses: packagrio/action-releasr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_email: 'julien@vinet.dev'
          author_name: 'Julien Vinet'

      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_assets: 'src/dist/windows/LostArkFishingUI.exe'
          author_email: 'julien@vinet.dev'
          author_name: 'Julien Vinet'
